/* Full profile view: preserves the editorial image language while offering clear continuation into a chat route. */
import { useState } from "react";
import { Link, useRoute } from "wouter";
import { Bookmark, BookmarkCheck, Check, ChevronRight, Image as ImageIcon, MessageCircle, Play, Sparkles } from "lucide-react";
import DiscoveryRouteShell from "@/components/DiscoveryRouteShell";
import { getRouteProfile, routeProfiles } from "@/lib/routeProfiles";

export default function CharacterProfile() {
  const [, params] = useRoute("/profiles/:slug");
  const profile = getRouteProfile(params?.slug);
  const [saved, setSaved] = useState(false);
  const [tab, setTab] = useState<"Story" | "Scenes" | "Details">("Story");
  if (!profile) return <DiscoveryRouteShell active="profile" eyebrow="CHARACTER PROFILE"><section className="route-unavailable"><Sparkles size={28} /><p>PROFILE NOT AVAILABLE</p><h1>This profile is still being prepared.</h1><Link href="/">Return to discovery</Link></section></DiscoveryRouteShell>;
  return <DiscoveryRouteShell active="profile" eyebrow="CHARACTER PROFILE"><section className="profile-page">
    <div className="profile-hero-card"><div className="profile-hero-visual"><img src={profile.image} alt={`${profile.name} portrait`} /><div className="profile-hero-fade" /><span className="profile-state-chip">{profile.status === "Series" ? <Play size={10} fill="currentColor" /> : <Sparkles size={11} />}{profile.status}</span></div><div className="profile-hero-copy"><p className="profile-kicker">{profile.category.toUpperCase()} CHARACTER</p><h1>{profile.name} <span>{profile.age}</span></h1><p>{profile.tagline}</p><div className="profile-hero-meta"><span><Check size={13} /> Available to talk</span><span><ImageIcon size={13} /> 12 scenes</span></div><div className="profile-actions"><button className={`profile-save-action ${saved ? "saved" : ""}`} onClick={() => setSaved(!saved)}>{saved ? <BookmarkCheck size={16} fill="currentColor" /> : <Bookmark size={16} />}{saved ? "Saved to collection" : "Save profile"}</button><Link href={`/chat/${profile.slug}`} className="profile-chat-action"><MessageCircle size={17} />Start a chat</Link></div></div></div>
    <div className="profile-content-grid"><div className="profile-editorial"><div className="profile-tabs" role="tablist">{(["Story", "Scenes", "Details"] as const).map(item => <button role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</div>{tab === "Story" && <article className="profile-prose"><p className="profile-dropcap">{profile.about}</p><p>There is an easy rhythm to getting to know {profile.name}. Start with something small—a place you want to revisit, a question you are turning over, or the first detail you noticed today—and let the exchange build from there.</p><div className="profile-quote">“Good conversations make the familiar feel new again.”</div></article>}{tab === "Scenes" && <div className="profile-scenes">{profile.gallery.map((image, index) => <figure key={image}><img src={image} alt={`${profile.name} scene ${index + 1}`} /><figcaption>Scene 0{index + 1}</figcaption></figure>)}</div>}{tab === "Details" && <div className="profile-details-list">{profile.details.map(detail => <div key={detail}><span><Check size={15} /></span><p>{detail}</p></div>)}</div>}</div><aside className="profile-aside"><div className="profile-aside-card"><p>CONVERSATION STARTERS</p><button onClick={() => setTab("Story")}>What made today memorable?<ChevronRight size={16} /></button><button onClick={() => setTab("Details")}>What are you curious about lately?<ChevronRight size={16} /></button><button onClick={() => setTab("Scenes")}>Show me a favorite kind of day.<ChevronRight size={16} /></button></div><div className="profile-aside-card compact"><p>DISCOVER MORE</p><div className="mini-profile-grid">{routeProfiles.filter(candidate => candidate.slug !== profile.slug).slice(0, 3).map(candidate => <Link href={`/profiles/${candidate.slug}`} key={candidate.slug}><img src={candidate.image} alt={candidate.name} /><span>{candidate.name}</span></Link>)}</div></div></aside></div>
  </section></DiscoveryRouteShell>;
}
